name: flutter_bloc_workshop
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # is a predictable state management library that helps to manage the state of the application in a clear and organized way.
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
 
 
  # Is a simple service locator for dependency injection. It enhances code organization and provides a clean way to manage dependencies.
  get_it: ^7.6.4
  
  # Being able to compare objects in Dart
  equatable: ^2.0.5

  # Fetch Data From Api
  dio: ^5.3.3
  #Lightweight and customizable BLoC state management library logger on talker base.Talker - Advanced exception handling and logging for dart/flutter applications 🚀
  talker_bloc_logger: ^2.2.0
  talker_dio_logger: ^2.3.0

  #A declarative router for Flutter based on Navigation 2 supporting deep linking, data-driven routes and more
  go_router: ^11.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.1.4

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
